### ISSUE TITLE
Update the setup of the IME

### ISSUE THREAD

**Issue by frankliu197** [saschanaz/ime-rs#1]
With InstallShield being paid/not available on Visual Studio 2019, could you explain your workflow on how to setup the sample code and start coding.

I would like to code an IME in rust but I do not know how to get started

Thank you very much, 
Frank

**Comment by saschanaz** [comment]
(Note that only the small part of the code is written in Rust for now)

1. Make sure rust tools are installed and globally available
2. Build the project on VS2019, probably as a debug build. The rust code will be built automatically as a pre-build step.
3. Register the dll via `regsvr32 cpp/x64/Debug/SampleIME.dll`
4. Load the IME via <kbd>Win+Space</kbd>

To debug, open Notepad and attach to the Notepad process.
To rebuild, make sure no process is using it. `tasklist /m cpp/x64/Debug/SampleIME.dll` shows which process is using the dll. Kill them all and rebuild.

**Comment by frankliu197** [comment]
![image](https://user-images.githubusercontent.com/23513458/133146566-2ecfc972-02cf-4c13-b560-fbcbd81e206f.png)
For the debug step, I've been getting many linker errors. 

Also for the original microsoft example, I have no clue how to create the SampleIME.dll 
![image](https://user-images.githubusercontent.com/23513458/133147106-cb99991d-364b-4070-bdac-a9c19262fcc2.png)

This is my first windows project so i'm pretty confused

**Comment by saschanaz** [comment]
Hmmm, that implies the Rust code is not being built or the library is not properly being referenced, not sure what's going on there. Are there other errors other than linker ones?

**Comment by frankliu197** [comment]
Yes all of them are linker errors.

**Comment by frankliu197** [comment]
And for 64 bit I get:
![image](https://user-images.githubusercontent.com/23513458/133151047-60dd80d0-d7d2-4509-802e-6b9b533f7835.png)

I am using 64 bit rust

**Comment by saschanaz** [comment]
Oh oops it assumes you have powershell 6+ installed

**Comment by saschanaz** [comment]
And it also means I should really just remove the Win32 build profile since I don't care of it. Didn't know it had no prebuild step.

**Comment by frankliu197** [comment]
Thank you the build worked!

The only issue now is by changing to rust ime, my tabs close and I get a blank white screen.

![Uploading 20210913_194957.jpg…]()

**Comment by saschanaz** [comment]
It seems your screenshot failed to be uploaded 👀 but you may debug it by:

1. Open Notepad
2. Attach to the Notepad process
3. Switch back to the Notepad window and switch to the rust IME
4. See an exception happens

**Comment by frankliu197** [comment]
![Uploading 20210914_130713.jpg…]()
I hope it works this time

**Comment by frankliu197** [comment]
![Uploading 20210914_130713.jpg…]()

**Comment by frankliu197** [comment]
![image](https://user-images.githubusercontent.com/23513458/133320534-d8f3f78f-e66f-4442-a93d-7bf4920c97a2.png)
This is what I get

**Comment by saschanaz** [comment]
Ahhh right, you also have to copy the cpp/SampleIME/Dictionary/SampleIMESimplifiedQuanPinUtf8.txt into x64/Debug. This should become automatic but not yet.

Seems we really need a properly documented build steps 😬, sorry!

**Comment by saschanaz** [comment]
To be fair it's not *my* fault, it's the original demo project's fault 🙄

**Comment by frankliu197** [comment]
I got everything working and I can kind of? debug it. It seems like a pain to debug/reverse engineer it.

**Comment by saschanaz** [comment]
Updated README after several months 😄 6d046e2
