### ISSUE TITLE
Debug build failed to compile

### ISSUE THREAD

**Issue by alenpaulvarghese** [saschanaz/ime-rs#16]
OS: WIndows 11
IDE: Visual studio 2022
rustc: 1.72.0

steps: 
 - cloned this project
 - double click on cpp/SampleIME.sln
 - ran debug build on the configuration x64

any pointers in the right direction is much appreciated.

![image](https://github.com/saschanaz/ime-rs/assets/38587581/19647143-fa9b-4ad5-882d-6b89221ec907)

**Comment by saschanaz** [comment]
I can repro this, perhaps something is broken by tool updates? I'll take a look.

**Comment by saschanaz** [comment]
Fixed by 8d4838049d658b05dc63a04400a0a150cf3b3eaf. Please try again with the latest commit and ping back if that doesn't work. Thank you for reporting this!

**Comment by alenpaulvarghese** [comment]
Sorry for the late reply. It seems to be working fine now. Thanks for the quick fix.
